# What is a TENSOR ?

- In mathematics, a tensor is an algebraic object that describes a relationship between sets of algebraic objects related to a vector space. Objects that tensors may map between include vectors and scalars, and even other tensors.
- Tensors are simply mathematical objects that can be used to describe physical properties, just like scalars and vectors. In fact tensors are merely a generalisation of scalars and vectors; a scalar is a zero rank tensor, and a vector is a first rank tensor.

# How different is VECTOR from TENSOR ?

- The tensor is a more generalized form of scalar and vector. Or, the scalar, vector are the special cases of tensor. If a tensor has only magnitude and no direction (i.e., rank 0 tensor), then it is called scalar. If a tensor has magnitude and one direction (i.e., rank 1 tensor), then it is called vector.

# Installing Pytorch

In [1]:
!pip install torch torchvision

# Initializing the Tensors and its Attributes

In [2]:
import torch

In [ ]:
# Initializing a tensor.
# Setting device type to 'cuda', if not set then it will go with 'cpu' by default.
# Setting datatype to float32.

my_tensor=torch.tensor([[1,3,4],[2,4,5]],dtype=torch.float32, device='cuda')

In [ ]:
my_tensor

tensor([[1., 3., 4.],
        [2., 4., 5.]], device='cuda:0')

## Other Tensor Initialization techniques.

- **torch.empty( )** Returns a tensor filled with uninitialized data. The shape of the tensor is defined by the variable argument size.

In [ ]:
new_tensor = torch.empty(size=(2,3))

In [ ]:
print(new_tensor)

tensor([[-3.2374e-24,  3.0764e-41, -1.9940e+35],
        [ 3.0764e-41, -3.2211e-24,  3.0764e-41]])


In [ ]:
new_tensor = torch.empty(size=(4,3))

In [ ]:
new_tensor

tensor([[-7.7884e+37,  3.0764e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 4.4721e+21,  1.5956e+25,  4.7399e+16],
        [ 3.7293e-08,  1.4838e-41,  0.0000e+00]])

- **torch.zeros( )** returns a tensor with zeros of prescribed shape.

In [ ]:
new_tensor = torch.zeros(size=(3,3))

In [ ]:
new_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

- **torch.rand( )** returns a tensor that contains a set of random numbers drawn from a uniform distribution in the interval [0,1). The shape is defined by the variable parameter sizes.

In [ ]:
new_tensor = torch.rand(size=(3,4))

In [ ]:
new_tensor

tensor([[0.5880, 0.7131, 0.3825, 0.6020],
        [0.4232, 0.6354, 0.2485, 0.0531],
        [0.7695, 0.6156, 0.4987, 0.1733]])

- **torch.randn( )** returns a tensor, which contains a set of random numbers drawn from a standard normal distribution (mean 0, variance 1, Gaussian white noise), the shape is defined by the variable parameter sizes .

In [ ]:
new_tensor = torch.randn(size=(3,3))

In [ ]:
new_tensor

tensor([[ 0.2382,  1.7844,  0.0368],
        [ 0.6544, -0.7989, -0.8466],
        [-1.1326, -0.3392,  0.1645]])

In [ ]:
# Variance of nearly one.
new_tensor.var()

tensor(0.8055)

In [ ]:
# Mean of nearly zero
new_tensor.mean()

tensor(-0.0265)

- **torch.ones( )** returns a tensor with ones.

In [ ]:
new_tensor = torch.ones(size=(3,3))

In [ ]:
new_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

- **torch.eye( )** returns an Identity Matrix or tensor.

In [ ]:
# 'n' being number of rows and 'm' being number of columns.
new_tensor = torch.eye(n=3,m=3)

In [ ]:
new_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
new_tensor = torch.eye(3,4)

In [ ]:
new_tensor

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

- **torch.arrange( )** Returns a 1-D tensor of size [(end-start)/(step)]
with values from the interval [start, end) taken with common difference step beginning from start.

In [5]:
new_tensor = torch.arange(start=2,end=7,step=1)

In [6]:
new_tensor

tensor([2, 3, 4, 5, 6])

**torch.linspace( )** Creates a one-dimensional tensor of size steps whose values are evenly spaced from start to end, inclusive.

In [7]:
new_tensor = torch.linspace(0.1,1,5)

In [8]:
new_tensor

tensor([0.1000, 0.3250, 0.5500, 0.7750, 1.0000])

**torch.empty( )** with **Normal Distribution.**

In [13]:
new_tensor = torch.empty(size=(4,4)).normal_(mean=0, std=1)

In [14]:
new_tensor

tensor([[-0.2428, -0.2718, -2.0102, -0.7468],
        [ 1.2908, -0.4575, -0.5068,  0.5164],
        [-0.4806, -1.1528,  2.5138,  1.8448],
        [ 1.0138, -0.0926, -0.7775,  0.1519]])

In [15]:
new_tensor.mean(), new_tensor.std()
# Approximately equal to 0, 1.

(tensor(0.0370), tensor(1.1563))

**torch.empty( )** with **Uniform Distribution.**

In [17]:
new_tensor = torch.empty(size=(4,4)).uniform_(0,1)

In [18]:
new_tensor

tensor([[0.1676, 0.6292, 0.7459, 0.7882],
        [0.8520, 0.3296, 0.1846, 0.2017],
        [0.7656, 0.0019, 0.0240, 0.0306],
        [0.5341, 0.9814, 0.0143, 0.3979]])

**torch.daig( )** 
- If input is a vector (1-D tensor), then returns a 2-D square tensor with the elements of input as the diagonal.

- If input is a matrix (2-D tensor), then returns a 1-D tensor with the diagonal elements of input.

In [24]:
input_vector = torch.ones(3)

In [31]:
new_tensor = torch.diag(input_vector, diagonal=0)

In [32]:
new_tensor

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

# Initializing tensors and converting them to other Data types

In [11]:
# Initializing a tensor.
new_tensor = torch.arange(5)

In [12]:
new_tensor

tensor([0, 1, 2, 3, 4])

In [18]:
new_tensor.dtype
# We can check its of integer datatype.

torch.int64

- converting it to **boolean** datatype by using **.bool( )** method.

In [14]:
bool_tensor = new_tensor.bool()

In [15]:
bool_tensor

tensor([False,  True,  True,  True,  True])

In [16]:
bool_tensor.dtype
# It got converted to Boolean type.

torch.bool

- converting it to **short(Int16)** datatype by using **.short( )** method.


In [19]:
short_tensor = new_tensor.short()

In [20]:
short_tensor

tensor([0, 1, 2, 3, 4], dtype=torch.int16)

In [22]:
short_tensor.dtype
# Int16 is of Short type.

torch.int16

- converting it to **long(Int64)** datatype by using **.long( )** method.



In [23]:
long_tensor = new_tensor.long()

In [24]:
long_tensor

tensor([0, 1, 2, 3, 4])

In [25]:
long_tensor.dtype
# Int64 is of long type.

torch.int64

- converting it to **half(Float16)** datatype by using **.half( )** method.

In [26]:
half_tensor = new_tensor.half()

In [27]:
half_tensor

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)

In [28]:
half_tensor.dtype
# Float16 is of half type.

torch.float16

- converting it to **Float32** datatype by using **.float( )** method.

In [29]:
float_tensor = new_tensor.float()

In [30]:
float_tensor

tensor([0., 1., 2., 3., 4.])

In [31]:
float_tensor.dtype
# Float by default is of float32.

torch.float32

- converting it to **double(Float32)** datatype by using **.double( )** method.

In [32]:
double_tensor = new_tensor.double()

In [33]:
double_tensor

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

In [35]:
double_tensor.dtype
# Float64 by default.

torch.float64

# Converting Arrays to Tensors and Vice-versa.

In [36]:
import numpy as np

In [37]:
numpy_array = np.zeros((5,5))

In [41]:
type(numpy_array)
# Its of numpy array type.

numpy.ndarray

In [39]:
torch_array = torch.from_numpy(numpy_array)

In [42]:
type(torch_array)
# Easily got converted to a torch tensor.

torch.Tensor

In [43]:
numpy_array_back = torch_array.numpy()

In [45]:
type(numpy_array_back)
# Converted back again to numpy array.

numpy.ndarray

**Thank You !**