# Involving Maths and Comparision Operators

## Basic Math operators

In [1]:
# Importing torch
import torch

In [ ]:
# Let us declare two tensors.
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([5,6,7])

- **Adding Two Tensors**

In [ ]:
# Way 1 using built-in functions.
out_tensor = torch.empty(3)

In [ ]:
a_sum_b = torch.add(tensor_a, tensor_b)

In [ ]:
a_sum_b

tensor([ 6,  8, 10])

In [ ]:
# Way 2 adding them directly.
a_sum_b = tensor_a + tensor_b

In [ ]:
a_sum_b

tensor([ 6,  8, 10])

**Subtraction between two tensors.**

In [ ]:
a_sub_b = tensor_a - tensor_b

In [ ]:
a_sub_b

tensor([-4, -4, -4])

**Division of Two tensors**

In [ ]:
a_divide_b = torch.true_divide(tensor_a,tensor_b)

In [ ]:
a_divide_b
# Element wise division.

tensor([0.2000, 0.3333, 0.4286])

In [ ]:
a_divide_b = tensor_a/tensor_b

In [ ]:
a_divide_b
# Even it does the same thing.

tensor([0.2000, 0.3333, 0.4286])

**Inplace operations**
- An in-place operation is an operation that changes directly the content of a given Tensor without making a copy. Inplace operations in pytorch are always postfixed with a _, like .add_() or .scatter_(). Python operations like += or *= are also inplace operations.

In [ ]:
tensor_a

tensor([1, 2, 3])

In [ ]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10])

- After applying the inplace operator the value of the tensor got changed for permanently.

In [ ]:
tensor_a

tensor([ 6,  8, 10])

**NOTE** : It is an equivalent of *tensor_a = tensor_a + tensor_b*

**Applying Exponents on tensors.**


In [ ]:
tensor_a = torch.tensor([1,2,3,4])

In [ ]:
tensor_a

tensor([1, 2, 3, 4])

In [ ]:
exp_tensor_a = tensor_a.pow(2)

In [ ]:
exp_tensor_a

tensor([ 1,  4,  9, 16])

In [ ]:
tensor_b = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])

In [ ]:
tensor_b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
exp_tensor_b = tensor_b.pow(2)

In [ ]:
exp_tensor_b

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

- We can understand that this is gonna apply power on single elements at a time not confusing it with the matrix multiplication.

In [ ]:
# Other equivalent for this with a more pythonic code will be as follows.
exp_tensor_a = tensor_a**2

In [ ]:
exp_tensor_a

tensor([ 1,  4,  9, 16])

In [ ]:
# Inplace operator would be.
tensor_a.pow_(2)

tensor([ 1,  4,  9, 16])

In [ ]:
tensor_a
# Changes got permanent with this Inplace operator.

tensor([ 1,  4,  9, 16])

## Comparision between the Tensors

In [ ]:
tensor_a>0

tensor([True, True, True, True])

In [ ]:
tensor_b<0

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
tensor_c = tensor_b

In [ ]:
tensor_b == tensor_c
# Tensors with equal shape can be compared or else its gonna throw an exception.

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

# Matrices

**Matrix Multiplication**
- **Rule:** always remember if matrixA is of m rows amd n columns and matrixB is of p rows and q columns then for Multiplication ***n==p*** is True.

In [6]:
# Initializing two matrices.
matrixA=torch.rand((3,6))
matrixB=torch.rand((6,3))

In [8]:
matrixA, matrixB

(tensor([[0.8670, 0.2192, 0.4036, 0.7511, 0.0930, 0.1595],
         [0.0713, 0.3994, 0.0611, 0.9112, 0.5816, 0.2688],
         [0.4340, 0.2112, 0.7247, 0.0151, 0.2244, 0.1177]]),
 tensor([[0.4170, 0.8120, 0.8982],
         [0.4306, 0.6570, 0.6875],
         [0.0131, 0.0806, 0.5084],
         [0.4071, 0.8747, 0.9344],
         [0.3930, 0.4247, 0.3696],
         [0.1423, 0.9799, 0.9119]]))

In [9]:
multi_matrix = torch.mm(matrixA, matrixB)

In [12]:
multi_matrix, print(multi_matrix.shape)

torch.Size([3, 3])


(tensor([[0.8263, 1.7333, 2.0163],
         [0.8403, 1.6327, 1.6812],
         [0.3925, 0.7733, 1.1078]]), None)

**Matrix Exponentiation:**
- It's the multiplication of a matrix with itself for n times the power raised, Ex: matrixA power 2 = matrixA multiplied by matrixA.

In [14]:
matrix = torch.rand((3,3))

In [16]:
matrix

tensor([[0.0062, 0.1620, 0.2833],
        [0.0918, 0.2466, 0.7102],
        [0.9171, 0.0357, 0.6187]])

In [15]:
matrix_power_3 = matrix.matrix_power(3)

In [17]:
matrix_power_3

tensor([[0.2742, 0.0675, 0.2948],
        [0.6008, 0.1571, 0.6591],
        [0.6325, 0.1615, 0.7039]])

**Element wise tensor Multiplication:**
- Multiplying the tensors with respect to elements.
- Its very much different from Matrix multiplication as normal multiplication fails when we have tensors with different shapes.

In [20]:
tensor_a = torch.tensor([[1,2,3],[4,5,6]])
tensor_b = torch.tensor([[6,5,4],[1,2,3]])

In [21]:
# Its just the element wise multiplication.
tensor_a*tensor_b

tensor([[ 6, 10, 12],
        [ 4, 10, 18]])

**Batch Matrix Multiplication:**
- Its the same matrix multipliction but happens with in a bunch of matrices.
- No. of matrices define the batch size.

In [32]:
batch_size = 32

In [34]:
batch_matrixA = torch.rand((batch_size,3,5))
batch_matrixB = torch.rand((batch_size,5,3))

In [35]:
multi_batch = torch.bmm(batch_matrixA, batch_matrixB)
# bmm stands for batch matrix multiplication.

In [38]:
# The same matrix multiplication with a batch size
multi_batch.shape

torch.Size([32, 3, 3])

# Vector(1D Tensor) product

**Dot product between vectors:**
- Only works when tensors are 1 Dimensional(1D).

In [25]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([6,5,4])

In [26]:
# Returns a Scalar Quantity.

dot_pro = torch.dot(tensor_a, tensor_b)

In [27]:
dot_pro

tensor(28)

**Cross product between vectors:**
- Only works when tensors are 1 Dimensional(1D).

In [28]:
cross_pro = torch.cross(tensor_a, tensor_b)

In [29]:
# Returns a vector normal to the plane of both the vectors.
cross_pro

tensor([-7, 14, -7])

# Boradcasting and other useful operations.
**Broad Casting:**
-  The term broadcasting describes how arrays are treated with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across, the broader array so that they have compatible shapes.
- Many PyTorch operations support NumPy's broadcasting semantics. In short, if a PyTorch operation supports broadcast, then its Tensor arguments can be automatically expanded to be of equal sizes (without making copies of the data).

In [2]:
# Braodcasting.
tensor_a = torch.rand((5,5))
tensor_b = torch.rand((1,5))

- Now there is no way that we can operate these matrices among eachother using any mathematical operations. But thanks to **Broad Casting** which made these kind of operations possible.


In [3]:
diff_tensor = tensor_a - tensor_b

In [4]:
diff_tensor

tensor([[ 0.7423,  0.0675, -0.3908, -0.0631,  0.2772],
        [-0.0226, -0.4442, -0.4760, -0.0275,  0.1015],
        [ 0.2722, -0.1632, -0.0133, -0.7561, -0.3427],
        [ 0.5648, -0.5169,  0.0581, -0.3464, -0.5625],
        [-0.2313,  0.1324,  0.4569,  0.0743, -0.0416]])

- what happened in the above cell is that the tensor_b was removed from every row of tensor_a and thats how exactly broadcasting works.

In [5]:
# Can also use power operations.
tensor_a**(tensor_b)

tensor([[0.9981, 0.8435, 0.3420, 0.7681, 1.0000],
        [0.6905, 0.3970, 0.1893, 0.7977, 0.8696],
        [0.8501, 0.6573, 0.7012, 0.0452, 0.4970],
        [0.9501, 0.3190, 0.7509, 0.5184, 0.2662],
        [0.3707, 0.8930, 0.9857, 0.8807, 0.7576]])

# Other useful Operations.

In [28]:
x= torch.tensor([1,2,3])

In [15]:
# Sum of the elements in a tensor.

sum_of_x = torch.sum(x,dim=0)

In [16]:
sum_of_x

tensor(6)

- **Max and Min** of a tensor.

In [29]:
# Maximum valued element from the tensor.
value, index = x.max(dim=0)

In [30]:
print(value)

tensor(3)


In [31]:
# Minimun valued element from the tensor.
value, index = x.min(dim=0)

In [32]:
print(value)

tensor(1)


- **Playing with Dimensions and checking sum**

In [19]:
x= torch.tensor([[1,2,3],[3,4,5]])

In [25]:
# Sum of the elements in a tensor with different dim value when the tensor is 2D.
sum_of_x_dim2 = torch.sum(x,dim=-2)
sum_of_x_dim = torch.sum(x,dim=-1)
sum_of_x_dim0 = torch.sum(x,dim=0)
sum_of_x_dim1 = torch.sum(x,dim=1)

In [26]:
print('Sum of x with dim=-2 is:{}'.format(sum_of_x_dim2))
print('Sum of x with dim=-1 is:{}'.format(sum_of_x_dim))
print('Sum of x with dim=0 is:{}'.format(sum_of_x_dim0))
print('Sum of x with dim=1 is:{}'.format(sum_of_x_dim1))

Sum of x with dim=-2 is:tensor([4, 6, 8])
Sum of x with dim=-1 is:tensor([ 6, 12])
Sum of x with dim=0 is:tensor([4, 6, 8])
Sum of x with dim=1 is:tensor([ 6, 12])


- **abs** value of a tensor. Which makes all values positive

In [37]:
tensor_a = torch.tensor([-1,2,4])

In [34]:
torch.abs(tensor_a)

tensor([1, 2, 4])

- **Argmin and Argmax** of tensors.

In [40]:
# Returns indices of the minimum and maximum values.
tensor_a.argmin(dim=0), tensor_a.argmax(dim=0)

(tensor(0), tensor(2))

- **Mean** of tensors.

In [43]:
# Mean of a tensor.
torch.mean(tensor_a.float(), dim=0)

tensor(1.6667)

- **Comparision** element wise of tensors.

In [44]:
# Element wise comparision of tensors.
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([3,2,1])
torch.eq(tensor_a, tensor_b)

tensor([False,  True, False])

- **Sorting** tensors.

In [47]:
# Sorting a tensor.
val, ind=torch.sort(tensor_b, dim=0)

In [48]:
print('Sorted tensor:{}'.format(val))
print('Indices of sorted array:{}'.format(ind))

Sorted tensor:tensor([1, 2, 3])
Indices of sorted array:tensor([2, 1, 0])


 **Clamping of tensors**
- If clips of the tensor in between the min and max values provided and then assigns min values to the elements lesser than the min threshold and assigns max value to the tensor which are higher than the max threshold.

In [49]:
tensor_a = torch.tensor([1,2,3,4,5,6,7,8])

In [51]:
torch.clamp(tensor_a,min=3,max=7)

tensor([3, 3, 3, 4, 5, 6, 7, 7])

- Using **any** and **all** to check the values of our choice.

In [52]:
new_tensor = torch.tensor([1,1,0,1,1])

In [53]:
new_tensor.any()

tensor(True)

In [54]:
new_tensor.all()

tensor(False)

# Thank You