# Importing PyTorch

In [1]:
import torch

# Tensor Indexing

In [ ]:
# Declaring 10 tensors at a time with each tensor being 1*10 shape.
batch_size  = 10
tensor_batch = torch.rand(10,10,1)

In [ ]:
tensor_batch.shape

torch.Size([10, 10, 1])

## Basic Indexing

- Picking up first tensor.

In [ ]:
tensor_batch[0]

tensor([[0.9973],
        [0.6209],
        [0.7938],
        [0.2927],
        [0.8947],
        [0.8071],
        [0.4581],
        [0.9098],
        [0.6260],
        [0.7411]])

- Picking up second tensor.

In [ ]:
tensor_batch[1]

tensor([[0.0818],
        [0.3850],
        [0.8719],
        [0.8685],
        [0.7441],
        [0.0409],
        [0.8789],
        [0.9979],
        [0.9880],
        [0.4926]])

- Picking first 3 tensors.

In [ ]:
tensor_batch[0:3]

tensor([[[0.9973],
         [0.6209],
         [0.7938],
         [0.2927],
         [0.8947],
         [0.8071],
         [0.4581],
         [0.9098],
         [0.6260],
         [0.7411]],

        [[0.0818],
         [0.3850],
         [0.8719],
         [0.8685],
         [0.7441],
         [0.0409],
         [0.8789],
         [0.9979],
         [0.9880],
         [0.4926]],

        [[0.3499],
         [0.2576],
         [0.5023],
         [0.3563],
         [0.4616],
         [0.8081],
         [0.0333],
         [0.1976],
         [0.8805],
         [0.9242]]])

- Getting first three elements of all tensors in the batch

In [ ]:
tensor_batch[:,0:3]

tensor([[[0.9973],
         [0.6209],
         [0.7938]],

        [[0.0818],
         [0.3850],
         [0.8719]],

        [[0.3499],
         [0.2576],
         [0.5023]],

        [[0.1930],
         [0.0848],
         [0.6464]],

        [[0.1258],
         [0.7163],
         [0.8157]],

        [[0.6659],
         [0.7845],
         [0.6112]],

        [[0.9918],
         [0.6093],
         [0.7552]],

        [[0.7000],
         [0.8483],
         [0.2938]],

        [[0.9124],
         [0.1357],
         [0.6674]],

        [[0.4488],
         [0.3542],
         [0.8706]]])

- first 3 elements of first three tensors 

In [ ]:
tensor_batch[0:3,0:3]

tensor([[[0.9973],
         [0.6209],
         [0.7938]],

        [[0.0818],
         [0.3850],
         [0.8719]],

        [[0.3499],
         [0.2576],
         [0.5023]]])

- Let us move to some more indexing options.

In [ ]:
x_tensor = torch.arange(0,9,1)

In [ ]:
x_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

we will take out elements from tensor for specific indexes only.

In [ ]:
indices_list = [1,3,4,7]

In [ ]:
# Elements at given indices.
x_tensor[indices_list]

tensor([1, 3, 4, 7])

## Indexing through **Matrices**.

In [ ]:
matrixA = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

In [ ]:
matrixA

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])

In [ ]:
# Selecting rows and columns that we need.
selected_rows = [0,2]
selected_cols = [1,3]

In [ ]:
# Result of matrix after indexing.
matrixA[selected_rows,selected_cols]

tensor([ 2, 14])

## More Indexing using **Mixed Comparision Operators.**

In [4]:
a_tensor = torch.arange(1,10)

In [5]:
a_tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a_tensor>2
# Returns Boolean Values only according to our condition

tensor([False, False,  True,  True,  True,  True,  True,  True,  True])

In [7]:
a_tensor[a_tensor>2]
# Returns values according to our condition.

tensor([3, 4, 5, 6, 7, 8, 9])

- Some more indexing....

In [10]:
a_tensor[(a_tensor>2) | (a_tensor>7)]
# OR operator.

tensor([3, 4, 5, 6, 7, 8, 9])

In [11]:
a_tensor[(a_tensor>2) & (a_tensor>7)]
# AND operator.

tensor([8, 9])

using ***torch.where( )***
- Return a tensor of elements selected from either x or y, depending on condition.


In [16]:
a_tensor.where(a_tensor<3,a_tensor**2)

tensor([ 1,  2,  9, 16, 25, 36, 49, 64, 81])

Its clear that whenever the element was less than the given condition it returned the same element, else we have returned the element to the power of twice.

- **Set** functionality on tensors using **.unique( )**

In [20]:
new_tensor = torch.tensor([1,2,2,3,4,5,5,5,6,7,8])

In [18]:
new_tensor.unique()
# Gives out the unique values.

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
new_tensor.numel()
# Length of tensor 

11

# Reshaping Tensors

In [22]:
tensor_a = torch.tensor([1,2,3,4,5,6,7,8])

In [24]:
tensor_a = tensor_a.view(1,8)

- We can look for the shape of our current tensor.

In [25]:
tensor_a.shape

torch.Size([1, 8])

- Converting it to a 2 cross 4 shaped tensor.

In [27]:
tensor_a.reshape(2,4)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

- Now converting it to 4 cross 2 shape.

In [28]:
tensor_a.reshape(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

- Now making two different tensors of 2 cross 2 shape.

In [29]:
tensor_a.reshape(2,2,2)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

- Let us make another matrix and make a **Transpose** of it.

***Transpose of a Matrix***:
- In linear algebra, the transpose of a matrix is an operator which flips a matrix over its diagonal; that is, it switches the row and column indices of the matrix A by producing another matrix, often denoted by Aᵀ.

In [30]:
matrix = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [31]:
matrix.shape

torch.Size([3, 3])

In [33]:
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
# Transpose of the Matrix.

transpose_matrix = matrix.t()

In [34]:
transpose_matrix

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Adding tensors by dimensions and reshaping it.
- **torch.cat( )**:Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [36]:
tensor_a = torch.tensor([[1,2,3],[4,5,6]])
tensor_b = torch.tensor([[7,8,9],[10,11,12]])

In [37]:
tensor_a.shape, tensor_b.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [39]:
# Concating along rows
torch.cat((tensor_a, tensor_b),dim=0)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [40]:
# Concating along columns.
torch.cat((tensor_a, tensor_b),dim=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

**Explanation:**
- Here firstly both of the tensors were concatenated along a given dimension.
- concating is different from adding.

- **Flattening** the whole tensor.

In [41]:
tensor_a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [44]:
tensor_a.view(-1)
# This is kind of unzipping operation.

tensor([1, 2, 3, 4, 5, 6])

# **THANK YOU**