# Importing PyTorch

In [1]:
import torch
import torch.nn as nn # It has almost all Layers and Activation functions.
import torch.optim as optim # It has a lot of Optimizers.
import torch.nn.functional as F # It has some Activation Functions as well.
from torch.utils.data import DataLoader
import torchvision.datasets as datasets
import torchvision.transforms as transforms

In [2]:
# Importing Other Important Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# What is AutoGrad ?
- <img src='https://miro.medium.com/max/1000/1*7w9w0tGu5pPSBeS6FbbzEQ.png' width=400 />

- This class is an engine to calculate derivatives (Jacobian-vector product to be more precise). It records a graph of all the operations performed on a gradient enabled tensor and creates an acyclic graph called the dynamic computational graph. 

# Why do we need AutoGrad ?
- After a Forward Propagation Neural Networks barely learns anything any thing and then it improves its performance using Optimization methods.
- <img src='http://media5.datahacker.rs/2021/01/11-1024x593.jpg' width=400 />
- All of the models uses Optimization techniques to improve the solution so as Neural Networks. We have bunch of different Optimization techniques available for Optimizing Neural Networks.
- The Most commonly KNown one is *Gradient Descent* which iteratively updates the weights such that the loss is penalized in succesive steps. And these steps are decided by a parameter called as *Learning Rate*.
- <img src='https://miro.medium.com/max/1400/1*tQTcGTLZqnI5rp3JYO_4NA.png' width=800 />
- This Task is carried away by Complex Calculus calculations which infact is much harder to implement from scratch when we have huge number of parameter's weights to be optimized.
- Luckily for us AutoGrad Package in Pytorch is there to do all those complex calculations by abstracting it and making it so easy to implement.

# Let us Explore this stuff using an Example

In [69]:
# Let us initialize some imaginary Weights.
Input_tensor = torch.tensor([2.,2.,2.,2.], requires_grad=True)

# Looping through Epochs.
for epoch in range(3):
  # This would be out model's Desired output.
  weight = 3
  desired_model_output = (Input_tensor*weight).sum()
  print(desired_model_output)
  # Doing backward Propagation.
  desired_model_output.backward()
  print(Input_tensor.grad)
  Input_tensor.grad.zero_()

tensor(24., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(24., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
tensor(24., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])


## Observation:
- As we can see the required weights to get that desired output is 3.
- The weight with which we have multiplied our desired output was seen in backpropagation step.
- This is how AutoGrad makes sure we reach out desired output using the optimum weights.

# **THANK YOU**